- README.md
- assets/out
PR that now properly handles the `additional_properties` part of the payload. Before this PR, the part parsing out the additional properties would only take the first one (if 2 were sent in).  Now works well for analyzing golang code in the `out` repo including `coverage.xml`, `report.xml` and `tests.xml` when used as:
```
- put: code-analysis
params:
project_path: out
project_key: ((repo)):((branch))
sources: "."
additional_properties:
sonar.inclusions: "**/**.go"
sonar.projectName: ((repo))
```
Also removed the requirement on sonar.login seeing as you can have a SonarQube instance which does not require this (for example if you run the default deployment in a k8s cluster).
> Fix to the parsing of additional_properties

- README.md
- assets/common.sh
- assets/out
- assets/readproperties.awk
This should help in situations where you have to set dynamic properties
for the scanner in a previous task. All these properties should then be
written to a single file which can then be used here.
> New `additional_properties_file` out-param

- assets/in
Fix for #31 
Here's the Sonarqube [documentation](https://docs.sonarqube.org/display/DEV/Web+API) for using UserToken. The curl command has to be like,
```
curl -u THIS_IS_MY_TOKEN: https://sonarqube.com/api/user_tokens/search
```
> Handling Sonar UserToken

- assets/in
This is the fix for issue #33 when the cathive sonar resource fails silently if the curl command fails
when the curl command fails the resource should re-try and not fail immediately.
> Error handling for the sonar task status

- README.md
- assets/out
We use the [Bitbucket PR resource](https://github.com/zarplata/concourse-git-bitbucket-pr-resource) to run Sonar analysis on each pull requests.
We do not use the Sonar multi-branching feature so we need to compute a new Sonar project key for every pull requests.
The Sonar project key is available in a file and not in a static variables
We add the parameter `project_key_file` to achieve this goal.
It works exactly like the `project_version_file` parameter.
> Add support for project_key_file parameter

- README.md
- assets/check
- assets/common.sh
- assets/in
- assets/out
Support wildcards convert to comma-separated paths:
* `sources`
* `tests`
* `sonar.jacoco.reportPaths` in `additional_properties`
> Add support for convert wildcards to comma-separated paths.

- assets/common.sh
if the path does not exist, rather than fail/block the build, it can pass the same str as is with wildcards.
Sonar runner will still process other metrics like bugs, code smells, vulnerabilities, duplications etc.
```
INFO: Sensor JaCoCoSensor [java]
13:11:11
INFO: JaCoCo report not found: '**/build/jacoco/test.exec'
13:11:11
INFO: Sensor JaCoCoSensor [java] (done) | time=1ms
```
It will push code coverage metric as 0% - this can later be gated based on vmc policy (coverage >70%)
> Warning about path not exist, instead of fail/block the build.

- assets/common.sh
- assets/in
- test/mocks/qualitygates_project_status.json
- test_common.sh
example more output metadata: 
```json
{
"name": "new_coverage",
"value": "82.50562381034781"
},
{
"name": "new_blocker_violations",
"value": "14"
},
{
"name": "new_critical_violations",
"value": "1"
},
{
"name": "new_sqale_debt_ratio",
"value": "0.6562109862671661"
},
{
"name": "reopened_issues",
"value": "0"
},
{
"name": "open_issues",
"value": "17"
},
{
"name": "skipped_tests",
"value": "0"
}
```
> add metadata as qualitygates project status conditions

- AUTHORS.md
- CHANGELOG.md
- README.md
- assets/common.sh
Broaden scope of wildcard path support (properties ending with `.reportPaths`) on output. And a few doc corrections.
With this change I'm able to use this Concourse resource type with my Go projects. In particular, this now works for key `sonar.go.coverage.reportPaths`:
```
- put: code-analysis
params:
project_path: ((dev_branch))
project_key: "((sonarqube_team)).((component))"
sources: ["."]
tests: ["."]
additional_properties:
sonar.go.govet.reportPaths: "../app/govet.out"
sonar.go.golint.reportPaths: "../app/golint.out"
sonar.go.tests.reportPaths: "../app/gotest.out"
sonar.go.coverage.reportPaths: "../app/*_coverage.out"
#https://docs.sonarqube.org/latest/analysis/languages/go/
sonar.exclusions: "**/*_test.go,**/vendor/**"
sonar.test.inclusions: "**/*_test.go"
sonar.test.exclusions: …
```
> Broaden Scope of Wildcard Path Support

- assets/out
Seems that payload was not being redirected to JQ in order to get the branch name from user params.
> Redirecting payload to JQ parsing command

- assets/in
With the original version I was having the following issue:
```
Waiting for compute engine result (sleep: 5s)...
Start parseing quality_gates...
/opt/resource/common.sh: line 234: OK: No such file or directory
/opt/resource/in: line 102: OK: No such file or directory
ERROR in /opt/resource/in : line 102 with exit code 1
```
I think would be safe to have a readonly variable for project status file. In my tests it fixed my issue.
> Assing project status file to readonly variable

- README.md
- assets/out
We are using SonarCloud and, in order to decorate our PRs, we missed this feature in the resource. This PRs aims to add support for PR decoration if the user is using SonarCloud and probably will work with Developer Edition. We could use the resource as is but would be very trick to create custom sonar-project.properties file containing the branch name and PR
> Add PR decoration support

- assets/out
This is the fix for the issue #55 the branch name from file is always overwritten, even if the branch_name parameter is not set.
> Fixed branch name from file being overwritten

- assets/out
This adds bitbucket pr support for bitbucket resources that use the `pull-request-info` file.
This includes the following:
https://github.com/cathive/concourse-bitbucket-pullrequest-resource
https://github.com/philicious/concourse-git-bitbucket-pr-resource
https://github.com/zarplata/concourse-git-bitbucket-pr-resource
> Add support for pr decoration on bitbucket pr resources.

- assets/common.sh
- assets/out
What's the requirement? - https://github.com/cathive/concourse-sonarqube-resource/issues/60
changes:
assets/out -> enable globstar, change directory to {project_path} before wildcard_convert
assets/common.sh -> removed {project_path}
Above changes work for paths with globstar and no globstar; for example:
```
sonar.exclusions: "functional-tests/**"
sonar.java.binaries: "server/build/classes/java/main"
sonar.java.test.binaries: "server/build/classes/java/test"
sonar.java.libraries.reportPaths: "**/build/libs/**/*.jar"
sonar.java.test.libraries.reportPaths: "**/build/libs/**/*.jar"
sonar.jacoco.reportPaths: "**/build/jacoco/*.exec"
```
> Enable globstar.

- README.md
- assets/out
This change enables correctly performing pull request analysis where the base branch is not the repository's default branch. `sonar.pullrequest.base` is configured based on pull request resource metadata instead of `sonar.branch.name`.
Previously, `sonar.branch.name` was used to set `sonar.pullrequest.base` and both parameters were passed to sonar-scanner. However, `sonar.branch.name` is incompatible with pull-request analysis resulting in scan failure. Not supplying `sonar.pullrequest.base` results in using the repository's default branch, which causes warnings and potentially incorrect diffs to be displayed in SonarQube when the base branch is not the repository's default branch.
> sonar.branch.name is incompatible with pull-request analysis

- assets/out
Hello,
The current version was broken on CLI as the resource was looking for a maven settings file.
This commit is fixing it by adding an IF condition before trying to guess its path.
I also found a problem with PR identification in the decorate_pr attribute.
At the top of the resource, there is a `cd ${project_path}`
Then all conditions are checking for `${project_path}/.git`. The problem is that with the cd occurring above, it will never find this project path as we are already in.
There were three options:
1/ use the absolute path in the configuration of the resource
2/ remove the cd project_path at the top of the resource
3/ prefix the project path with the absolute path to make all conditions passing correctly
I went with the third option that was the less modifying/destroying the …
> out: Fixing the error on CLI when maven settings file doesn't exist

- assets/out
When debug is set to `true`, the `-X` option is added to the `mvn`
command. However, the extra output from the command interferes with the
setting of the `maven_project_build_directory` variable.
A simple fix is to always remove the `-X` pattern from the `mvn`
command.
> Fix Maven Scan Types When Debug is Set to True

- .github/workflows/ci.yml
- Dockerfile
The following files have been modified and added:
- Added **.github/workflows/ci.yml** file to use buildx in github actions in order to build and push the image for both the platforms to dockerhub.
- In **Dockerfile** file **debian:jessie** image is not available for arm64 so replaced it with **debian:latest** image.
> Release docker image for arm64

- Dockerfile
- Maven 3.8.6 -> 3.8.7 (minor bump due to 3.8.6 missing from Apache CDN)
- NodeJS 14 -> 18 (bump to current recommended LTS build)
- TypeScript 3.9.7 -> 4.9.4 (3.9.7 is now nearly two years out of date)
Maven hash can be found https://downloads.apache.org/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.zip.sha512 to confirm value.
> Bump Maven / Node / TypeScript versions
